const orderHistory = [
  {
    orderPlacedDate: 'August 4, 2020',
    totalPrice: '$34.00',
    shipTo: 'JS Masher',
    orderNumber: '#114-3941689-8772232',
    deliveredDate: 'Delivered Aug 8, 2020',
    deliveryConfirmation: '',
    numberOfItemsOrdered: '1',
    itemDescription: 'JavaScript for impatient programmers',
    bookAuthor: 'Rauschmayer, Dr. Axel',
    returnWindow: 'Return window closed on Sep 7, 2020',
    itemPrice: '$31.55',
  },
  {
    orderPlacedDate: 'July 19, 2020',
    totalPrice: '$44.53',
    shipTo: 'JS Masher',
    orderNumber: '#113-9984268-1280257',
    deliveredDate: 'Delivered July 20, 2020',
    deliveryConfirmation:
      'Your package was delivered. It was handed directly to a resident.',
    numberOfItemsOrdered: '1',
    itemDescription: 'The Timeless Way of Building',
    bookAuthor: 'Alexander, Christopher',
    returnWindow: 'Return window closed on Aug 19, 2020',
    itemPrice: '$41.33',
  },
  {
    orderPlacedDate: 'July 4, 2020',
    totalPrice: '$17.22',
    shipTo: 'JS Masher',
    orderNumber: '#144-2875557-9059409',
    deliveredDate: 'Delivered July 7, 2020',
    deliveryConfirmation:
      'Your package was delivered. It was handed directly to a resident.',
    numberOfItemsOrdered: '1',
    itemDescription: 'Gamecube controller adapter. Super Smash Bros Switch...',
    bookAuthor: '',
    returnWindow: 'Return window closed on Aug 5, 2020',
    itemPrice: '$41.33',
  },
  {
    orderPlacedDate: 'July 3, 2020',
    totalPrice: '$138.93',
    shipTo: 'JS Masher',
    orderNumber: '#113-2883177-2648248',
    deliveredDate: 'Delivered July 5, 2020',
    deliveryConfirmation: '',
    numberOfItemsOrdered: '2',
    itemDescription: [
      'Gamecube Controller - Super Smash Bros',
      'The Art of Sql',
    ],
    bookAuthor: 'Faroult, Stephane',
    returnWindow: 'Return window closed on Aug 4, 2020',
    itemPrice: ['$94.95', '$33.99'],
  },
];
